[workspace]
members = [
    "core",
    "pwrs",
]
resolver = "2"

[package]
name = "king_of_engine_bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "king_of_tokyo"
path = "src/main.rs"

[dependencies]
king_core = { path = "./core" }
king_pwrs = { path = "./pwrs" }
rand = "0.8.5"